In [14]:
#Importação de bibliotecas
import numpy as np # np será o apelido desta biblioteca

In [9]:
temperaturas = np.array([30,40,50])
print(temperaturas)
print(type(temperaturas))

[30 40 50]
<class 'numpy.ndarray'>

In [11]:
media =np.mean(temperaturas)
print(media)

40.0

In [13]:
maior_valor = np.max(temperaturas)
print(maior_valor)

50

In [15]:
menor_valor = np.min(temperaturas)
print(menor_valor)

30

In [28]:
salarios = np.array([2,3,4,5,1,500])
media_salarios = np.mean(salarios)
print(f"{media_salarios:.2f}")

85.83

In [17]:
mediana = np.median(salarios)
print(mediana)

3.5

Desafio final:
- Criar um array de habitantes de 5 cidades do estado de SP
- Maior população
- Menor população
- Média de população
- Mediana

In [27]:
cidades = np.array([11900,1340,1340,840,780])
maior_população = np.max(cidades)
print ( maior_população)
menor_população = np.min(cidades)
print(menor_população)
media_população = np.mean(cidades)
print(media_população)
mediana_população = np.median(cidades)
print(mediana_população)

11900
780
3240.0
1340.0

In [24]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"data\dataset_aula1_numpy_pandas.csv")

#Exibindo a tabela

In [3]:
df

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0             1  Montagem          72.62          41.77           111      0
1             2  Usinagem          81.65          34.08           128      0
2             3  Usinagem          68.87          39.44           159      0
3             4  Usinagem          66.84          34.52            98      0
4             5  Usinagem          66.23          31.57            94      0
5             6  Usinagem          64.79          37.09            83      0
6             7  Usinagem          85.02          36.34           106      1
7             8  Inspeção          60.31          33.77           124      0
8             9  Montagem          75.84          29.65            92      0
9            10  Inspeção          68.38          28.93           145      1
10           11  Usinagem          76.31          35.48           149      0
11           12  Inspeção          74.79          33.37           134      0
12           13  Usinagem          76.31          36.51           154      0
13           14  Montagem          63.28          33.71           129      0
14           15  Montagem          64.98          33.24            83      0
15           16  Montagem          81.48          30.50           102      0
16           17  Montagem          79.62          39.68            85      1
17           18  Inspeção          69.80          27.20            91      0
18           19  Inspeção          77.16          47.45            99      0
19           20  Usinagem          73.30          39.77           119      1
20           21  Inspeção          79.77          38.04            91      0
21           22  Usinagem          71.76          35.16            80      0
22           23  Inspeção          74.16          31.93           149      0
23           24  Usinagem          74.69          32.34           123      1
24           25  Usinagem          74.03          32.71           145      1
25           26  Usinagem          75.96          38.70            93      0
26           27  Usinagem          60.80          37.18           159      0
27           28  Montagem          69.37          35.90           122      1
28           29  Montagem          70.28          35.04           103      0
29           30  Inspeção          73.53          32.84            82      0
30           31  Montagem          63.59          42.29           159      1
31           32  Inspeção          68.91          32.66           155      0
32           33  Inspeção          77.62          35.70           108      1
33           34  Inspeção          73.32          32.18           129      1
34           35  Usinagem          78.24          31.93           158      0
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [ ]:
#Criar uma nova coluna relacionando dados

#df["classificacao_temperatura"] = np.where(df["temperatura_c"]>=75,"Temperatura Alta","Temperatura Baixa")

In [ ]:
#Exibi o corpo da base
df.shape

(40, 6)

In [ ]:
#Exibi colunas
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     str
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), str(1)
memory usage: 2.0 KB

In [7]:
df.isna().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [9]:
df.notnull().sum()

id_registro      40
setor            40
temperatura_c    40
tempo_ciclo_s    40
producao_dia     40
falha            40
dtype: int64

In [10]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000

In [11]:
df["temperatura_c"]

0     72.62
1     81.65
2     68.87
3     66.84
4     66.23
5     64.79
6     85.02
7     60.31
8     75.84
9     68.38
10    76.31
11    74.79
12    76.31
13    63.28
14    64.98
15    81.48
16    79.62
17    69.80
18    77.16
19    73.30
20    79.77
21    71.76
22    74.16
23    74.69
24    74.03
25    75.96
26    60.80
27    69.37
28    70.28
29    73.53
30    63.59
31    68.91
32    77.62
33    73.32
34    78.24
35    68.47
36    75.62
37    78.50
38    76.19
39    68.64
Name: temperatura_c, dtype: float64

In [12]:
df[["temperatura_c","id_registro"]]

    temperatura_c  id_registro
0           72.62            1
1           81.65            2
2           68.87            3
3           66.84            4
4           66.23            5
5           64.79            6
6           85.02            7
7           60.31            8
8           75.84            9
9           68.38           10
10          76.31           11
11          74.79           12
12          76.31           13
13          63.28           14
14          64.98           15
15          81.48           16
16          79.62           17
17          69.80           18
18          77.16           19
19          73.30           20
20          79.77           21
21          71.76           22
22          74.16           23
23          74.69           24
24          74.03           25
25          75.96           26
26          60.80           27
27          69.37           28
28          70.28           29
29          73.53           30
30          63.59           31
31          68.91           32
32          77.62           33
33          73.32           34
34          78.24           35
35          68.47           36
36          75.62           37
37          78.50           38
38          76.19           39
39          68.64           40

In [13]:
df.head()

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [25]:
df["classificacao_temperatura"] = np.where(df["temperatura_c"]  >= 75,"alta","baixa")
df.head()

,id_registro,setor,temperatura_c,tempo_ciclo_s,producao_dia,falha,classificacao_temperatura
0,1,Montagem,72.62,41.77,111,0,baixa
1,2,Usinagem,81.65,34.08,128,0,alta
2,3,Usinagem,68.87,39.44,159,0,baixa
3,4,Usinagem,66.84,34.52,98,0,baixa
4,5,Usinagem,66.23,31.57,94,0,baixa